version: '3'
services:
  mock-oauth2:
    build: .
    ports:
     - "8090:8090"
    depends_on:
      - "mongodb"
    volumes:
      - ./config.yml:/app/mock-oauth2/config.yml

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mock-oauth2
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
